# Generated by Django 3.0.6 on 2022-04-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column_Type',
            new_name='ColumnType',
        ),
    ]
