# Generated by Django 3.0.6 on 2022-04-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220423_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.ColumnType'),
        ),
    ]
