# Generated by Django 3.0.6 on 2022-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220424_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_number',
            field=models.IntegerField(default=0, verbose_name='Column number'),
        ),
    ]
