# Generated by Django 3.0.6 on 2022-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_column_column_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_number',
            field=models.IntegerField(verbose_name='Column number'),
        ),
    ]
