# Generated by Django 3.0.6 on 2022-04-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220424_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='state',
            field=models.CharField(choices=[('1', 'Processing'), ('2', 'Ready')], default='1', max_length=2, verbose_name='State'),
        ),
    ]
