# Generated by Django 3.0.6 on 2022-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220425_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name='Modification date'),
        ),
    ]
